// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvKsdEOGWPZOqIQcpC95KXpcQlGnFjRpc',
    appId: '1:964761774165:web:0a0e46a0f623e7c9e1ccdc',
    messagingSenderId: '964761774165',
    projectId: 'vibho-hcm-9f41c',
    authDomain: 'vibho-hcm-9f41c.firebaseapp.com',
    storageBucket: 'vibho-hcm-9f41c.appspot.com',
    measurementId: 'G-N4EP3Y9R8Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3rbs1akj6muLifF6qrI9jTBcUKzIv9Q4',
    appId: '1:964761774165:android:e0274f4754353d83e1ccdc',
    messagingSenderId: '964761774165',
    projectId: 'vibho-hcm-9f41c',
    storageBucket: 'vibho-hcm-9f41c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRO6N32qKRJREi592xqzhIq2ksPWseJvQ',
    appId: '1:964761774165:ios:618c231b67000281e1ccdc',
    messagingSenderId: '964761774165',
    projectId: 'vibho-hcm-9f41c',
    storageBucket: 'vibho-hcm-9f41c.appspot.com',
    iosClientId: '964761774165-tmts91jke68alc26jlov5e7ho06anqpv.apps.googleusercontent.com',
    iosBundleId: 'com.example.vibeshr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRO6N32qKRJREi592xqzhIq2ksPWseJvQ',
    appId: '1:964761774165:ios:25bdefb8b69c12b2e1ccdc',
    messagingSenderId: '964761774165',
    projectId: 'vibho-hcm-9f41c',
    storageBucket: 'vibho-hcm-9f41c.appspot.com',
    iosClientId: '964761774165-2omd2045da9ptiilavai9v1hrn1j9uq1.apps.googleusercontent.com',
    iosBundleId: 'com.example.vibeshr.RunnerTests',
  );
}
